apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: community-keda
  namespace: bravo-core-ns
spec:
  scaleTargetRef:
    name: community-service

  minReplicaCount: 2
  maxReplicaCount: 5

  pollingInterval: 15        # HPA metrics 주기와 유사
  cooldownPeriod: 300        # HPA scaleDown과 동일

  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "70"